version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres-movie
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: movie_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow-webserver:
    build: ./airflow
    container_name: airflow-webserver-movie
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres-movie:5432/movie_db
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./data:/app/data
      - ./scripts:/opt/airflow/scripts 
      - ./dbt:/opt/airflow/dbt
    ports:
      - "8080:8080"
    command: >
      bash -c "
      airflow db init &&
      airflow users create --username admin --firstname admin --lastname admin --role Admin --email admin@example.com --password admin &&
      airflow webserver"

  airflow-scheduler:
    build: ./airflow
    container_name: airflow-scheduler-movie
    depends_on:
      - airflow-webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres-movie:5432/movie_db
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./data:/app/data
      - ./scripts:/opt/airflow/scripts 
      - ./dbt:/opt/airflow/dbt
    command: airflow scheduler

  python-movie:
    build:
      context: .
      dockerfile: ./airflow/Dockerfile
    container_name: python-movie
    depends_on:
      - postgres
    tty: true
    stdin_open: true
    entrypoint: /bin/bash
    command: -c "while true; do sleep 1000; done"
    volumes:
      - ./scripts:/app/scripts
      - ./data:/app/data
    environment:
      DB_HOST: postgres-movie
      DB_USER: airflow
      DB_PASS: airflow
      DB_NAME: movie_db
      DB_PORT: 5432

  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:1.7.14
    container_name: dbt-movie
    working_dir: /usr/app
    entrypoint: /bin/sh -c "tail -f /dev/null"   # <-- keeps container alive
    volumes:
      - ./movies_analytics:/usr/app
      - ./data:/usr/app/data
    environment:
      DBT_PROFILES_DIR: /usr/app
      DB_HOST: postgres-movie
      DB_USER: airflow
      DB_PASS: airflow
      DB_NAME: movie_db
      DB_PORT: 5432
    depends_on:
      - postgres

volumes:
  postgres_data: